source "https://rubygems.org"

ruby "~> 3.4.0"
gem "rails", "~> 8.0"
gem "puma", "~> 7.0"
gem "pg", "~> 1.6"
gem "bootsnap", require: false

group :development, :test do
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
  gem "rubocop-rails-omakase", require: false
end
