source "https://rubygems.org"

ruby "~> 3.4.0"
gem "rails", "~> 8.0"
gem "puma", "~> 7.0"
gem "pg", "~> 1.6"
gem "bootsnap", require: false

group :development, :test do
  gem "rubocop", "~> 1.80", require: false
  gem "rubocop-rails", "~> 2.33", require: false
  gem "rspec-rails"
end